coverage:
  require_ci_to_pass: true

  status:
    project:
      default:
        target: 99%
        threshold: 1%
        base: auto
        informational: true

    patch:
      default:
        target: 99%
        threshold: 1%
        informational: true