name: CIFuzz
on:
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/cifuzz.yml'
  push:
    branches: [main, master]
permissions:
  contents: read
jobs:
  fuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, memory]
    steps:
    - name: Build Fuzzers (${{ matrix.sanitizer }})
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@ba0e2e0 # v1.0.0
      with:
        oss-fuzz-project-name: 'gin'
        language: go
        sanitizer: ${{ matrix.sanitizer }}
    - name: Run Fuzzers (${{ matrix.sanitizer }})
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@ba0e2e0 # v1.0.0
      with:
        oss-fuzz-project-name: 'gin'
        language: go
        fuzz-seconds: 300
        sanitizer: ${{ matrix.sanitizer }}
        output-sarif: true
    - name: Upload Sarif
      if: steps.build.outcome == 'success'
      uses: github/codeql-action/upload-sarif@601d5b1 # v3.28.15
      with:
        sarif_file: cifuzz-sarif/results.sarif
        category: fuzz-${{ matrix.sanitizer }}
